apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: bharath-systemsync
  project: defaultproject
spec:
  blueprintConfig:
    name: test
    version: 1
  cloudCredentials: bharath-eks
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceTypes:
      - t3.large
      maxSize: 2
      minSize: 0
      name: bharat-ng
      version: "1.27"
      volumeSize: 80
      volumeType: gp3
    - amiFamily: WindowsServer2022FullContainer
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceTypes:
      - t3.large
      maxSize: 2
      minSize: 0
      name: bharat-ng-1
      tags:
        email: bharath.reddy@rafay.co
        env: dev
      volumeSize: 50
      volumeType: gp3
    metadata:
      name: bharath-systemsync
      region: us-west-2
      tags:
        email: bharath.reddy@rafay.co
        env: dev
      version: "1.27"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
