apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: karpenter
  namespace: default
spec:
  encryptedData:
    driverconfig.container.envs.ENV: AQAo9pNiD2vYkBKyU+s3zLSvLz3hR2+F5r993I2wPsU6uNbpAQJnlZvIT0fllcl6rmjMIIjP/W6xwO4gPJsZuwl6QFYkmdBWrFwj5Q/wjH2JN2HlB06P7UcGGdKk5oblJS1agLxILdMfp6BJH8gZ6Os1x1Ek2elhs2j9fnDl7HCdNEKbykj23EMJTedyLUFP9KYArGbMAWuqvZUB987Dcmc9ETIWcFsUJcKtV9nBwxOFY/LjmzbZbNvnOUa9GVM/TRLBkdzaIkoNtToRgKjADPZ3dhTZ57uYiJEFYfckWwPfw1+bsRt+O80gOTC+BYD42qA+MU0H8ujl+NJq0jBDujuEwC6w8r0YYFQIhC6pBrL6VIeijEQ=
    registry_credentials: AQC1mkbzzK9JvuFfw0VURNYiq/BRBo91NHAMfks7LyQ/qoMgsBHVSSpskNj7LCXPc0zJFOsskJ5LSt3RBEZvCk06a5igVacSQwEdnzyc+o4OnImtMnxOkUCH1io4idjBzWHb6ugHcpG5bM8rnwnEm2mj78hvM4wlHQlKGet0uz7aEuv12Qh1dW+nC0tNplLnUlWUuQCgFy48oXTl9vjGkfMw7FA1T3Mm17eY3yKF72BDr0a6aK64eFIrh0ayBNr4X2dDh1wl+c/OnazGl0jz5ovB97oJbyCv0TdfvhwHxl7gU5JxuXdf/vOO8CPut7GOX9DIKl5Lfd88zmO2s4JYWG4JgukoCgd9RYuyyccNERh9QfOy9KYpZ35xcIs=
  template:
    metadata:
      creationTimestamp: null
      name: karpenter
      namespace: default

