apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: nginxjjjjj
  project: bharath
spec:
  agents:
  - {}
  credentials:
    password: sealed://credentials.password
    username: bharath.reddy@rafay.co
  endpoint: https://github.com/bharath-rafay/getstarted.git
  secret:
    name: file://artifacts/nginxjjjjj/sealed-secret.yaml
  type: Helm
