apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: test
  project: bharath
spec:
  agents:
  - name: test1-git
  credentials:
    password: sealed://credentials.password
    username: bharath-rafay
  endpoint: https://github.com/bharath-rafay/git-sync.git
  secret:
    name: file://artifacts/test/sealed-secret.yaml
  type: Git
