apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/test/airflow-1.0.861-243250-20240105-hotfix-airflow-offcycle-120123-41cec2c6-image-243241-20240105-122releasehf-937f97e2.tgz
    type: Helm
  namespace: nginx
