apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test
  project: defaultproject
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/test/test.tgz
    type: Helm
  namespace: nginx
