apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gittest
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBxjHvBlf1sCAvghDb0RgK9NL7juoAERYsTj/Q4AZlhf4+j16+r48yHu94eYoMSyllGXrqDJoaI0+ZUI63JFTg3QQlhgVCJK5Cmf1WXHBX2OCu8i8pVeTpH4T8Kxnw0VyRYvfS9lrxlM/ZX4vuck+dDdUi/X/ntxJmubhDBW5LCRQNwoyOWX8f+eUqM9uL//DK1eQ97/3bTcvSkbUNpR36oGzrm6HgTp6jK5Ar/U3YNZwustpO8rPawFFstlCRsVVHa+C9y/znxOa1jLUjAtVMmCbQHi2LgpEAn1J70PYdHicr4S58akVPS1D5IhzYcnn8stC8sMt7EuBodIkkxBHU9xQypE6QQaS48lcVMUwAn/zEcgC65mx0Xv9o=
  template:
    metadata:
      creationTimestamp: null
      name: gittest
      namespace: default

