apiVersion: config.openshift.io/v1
kind: Image
metadata:
 annotations:
  release.openshift.io/create-only: "true"
name: cluster
spec:
 registrySources:
  allowedRegistries:
  - demoapp . com
  - demoapp3. com
  - example. com
  - quay.io
  - registry.redhat.io
  - image-registry.openshift-image-registry.svc:5000
