apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: template3
  namespace: default
spec:
  encryptedData:
    hook.terraform.deploy.init.before.infracost.options.container.env_vars.DOWNLOAD_TOKEN: AQBdLDth7Ima5H2wgogR1gyjwjypPWxER+caze1GuYq9KlbS8b5qdHEmPzrWtqzGElwPKMD1U+8pbFmX/0LbV5VXAaDxJqfOx681iOXN0tjJR6ZsVL8bfndGjbwsXA2sXcqoSqAUtFhrw+ne4hutKc/Z5Kq7eilxxRFnSt83BuKOdiioOVeYxk8qOsUN91hmGP2B9dkIEKx6ubwxlGAZSriptY6U8xogzH0zlUK8hgs5xUoWHzdRhp6QyIdPSp/hwaeIzYmyS6tZhbtcGa7vA/LE4LxwYgYxvhsJ9vMs+hMEtVH7lmjSdEgsAfEFkQsU2bzQ++Lkv9XgZFITfWmftXopLyPGRSo4R2f0fRSfmRGrWPF1TBt7jYw+sIlispfRVvSjqVAhgTkb4M2i7rZWvsHx1FuKv8Iwg2V9qRiTQmXiQiqOS7gaIXBg1vE1A9MlY31bXWCCASwRzKYtyL98mcA=
    hook.terraform.deploy.init.before.infracost.options.container.env_vars.DOWNLOAD_URL: AQAso5wJoPONjo1uuL+LlGV9xSZQ5NcA+6MGLGEyIBWyo4Ll4ZctoGAIS8AJoECnyN3TC/P7jwUIXhLE9q9GpxVsVAMJuSjjyIXYnG9AP+dAJt3hconsd+LxnaHWnOBBxL0EI1/qyLTGBcrMc9N/s+frEXWgovs5qSgnYiuPGHp7SubVIAF68Tj3ICbF4RqidxapypoFxqIOhPeYDKrEvA7DxionpkX0ceIoL281D7L7z4cnRI7qSUfWLaiHw6mbRr+cCeiQ+c0nDV0epw/+zMLL5wqV58sa6m7T9fHMXdGdqfswhUa2QM2qS6GlNNEDkm1IfpMhetPCoRuw0l0gxTZPPUmX71ngFvTK7m1/jLikNaetpr4/BtiCt+Ob9WsgrNc4C+E4fe9kujpe/buOer3KQE9ndQ5enj4oOp7ByvDcqLMHw2e2WJ65hUCv6Vs9Ox0W66+zDdIbSKPFOw9V
    hook.terraform.deploy.output.before.webhook.options.http.headers.X-TOKEN: AQBSUvSzlUVguz/0kCRVsVDjdVNl15GbMQJJW1Y2vDrOSCBOgDic9EznWrsNqM7R7hTuSXlCLp7+ASrA5jDx9yh/oIp/+n3TV8X/7Ze0VjcR14CeSDiKnw7OtJtVvwWmU8lyflnYOh85mZUAvL6SRY/LuiEhruZcy8krB8SH6oRr4/cY+A2JjhPvzdBBa4R3gnZHTmZbwrdp7FnR6+n3p8RSpE7VGdrltairXHxknikYhDSb6dMcBygYBtJQv06TGR9nzOb2gHsb/lQFQAqEJQYPacKkPt2z3r7dcZZxoZFQeM7rs9jJXbmGEPKddk4lk9pL5HEGK5BrJ8B27NIMqdie+NHqTTDzDgMb4lW0S04ZfUQie87O
  template:
    metadata:
      creationTimestamp: null
      name: template3
      namespace: default

