apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: template3
  namespace: default
spec:
  encryptedData:
    hook.terraform.deploy.init.before.infracost.options.container.env_vars.DOWNLOAD_TOKEN: AQAL7OyR8gmhMZ77zaeW12SLSt/pTsB7Eg08s9zHLqSRw2RMDyk6VpaCckU+PbiJ8sxBOEqvSDPeyQk480BpsaJH0Lz6wtd7vYEM0Hg8+5dmyOy3dppCKtCaT+YKLV09F6G61Q6mxXr2j5AGQjd9Jzi5MH6BIrvfMurmhCOPiAJAlSmoDn10igtkzNkh85q2Z67OmXRZrFr4wbczGMBpV9IhHsdojjH8hNOJlKEWH5iMwI+vJADjMP5WHpMrHv1xaQ3PooIHT3fklTF5M7n3IH8a0oUT/lrUE4yrAeIMoV2jQDLD+RQf1uvUyfbuXAJUoRQABSwLEIUih1Sx33wxEqVynOrOEdZG6H7eXph5lAN2MKyYyELvmLI9DcpY3mINZX+MuVC3EsRFP8jQO9pvw8494qJkQU1JbjH5w0sD7IB+P8Gz4AeGd8aoEpESXG2RRZ73jZ5gTcD+Qg3s8tV24VA=
    hook.terraform.deploy.init.before.infracost.options.container.env_vars.DOWNLOAD_URL: AQA6iVriAyClyxHQUueK12dLwLZDt2GLyp7fUKt5W+vYSVfwW3xU/XAojz4uaKav4E2ihucwnX9x6Cx3WPY/ZEbg6Pn9+sfJ6crB8fVeRWy+9C2n7EpQxyRLLkbtJnHE+CVs+peUA1+OykA1A3Iq70wXrgd/eKdWE2yP2HJfznmCB72NUxnWg68JJRjRUYgOCuPSutiehOI/QkYmZi1tryGdB9jf/WrKkJs3d37UPTcXlf+cGslRzVonW3IT4ApTxJ0W/0h/wsGV8iMSiwGUJBaxGBS14xJyagSZp8oi8e+AWdVwLiRXX/9mH/jT8+fmrOVyRhzoHkF0liAljz8TXRS0pOWq2kaba3p35aPxtFL5uebtrUPNF4FDaWf2zbFfak7j5dlPUBIiipEUK1+zRfwnGAJq6pEG0VlN9LYfJlPbC/tZwlG4cueSa4a7c1SY79EKKSyMzGv3YTn6TZVM
    hook.terraform.deploy.output.before.webhook.options.http.headers.X-TOKEN: AQBt8YgNNScpW5l8Yg0acKykneyiua29SX4OIvUqAVmLOqd/RI3QvUb5ZGEOSWQ4ixLCeRh/gAAOSBvCe3RE5PKdgiM4Qkc600h/sn/eTEhaVvQsCZJ9UtVYG3im7B0gbhknVrrMIcFBxo9R3Bp82fGcZXQvw2aDfxFwvPMhQgKjQxoZaYUn+yJIO3Y+rY+QB9QnlM8OQjfs6zZM0jyzi5G6UUIz0Dd781gWcNrjqljONeeJGQ6LNCKJY6vutfFSsSjR5hCGsctLxW2S9NXRiK7xame8N9axlwroHrEz0OY5Yu4NcZFnp+6vYcgdeUvAbwUJNlnrq04g/wYhXajUCDl6+DPPWkwTVIKI13PaNgO84nh5f5au
  template:
    metadata:
      creationTimestamp: null
      name: template3
      namespace: default

