apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: bharat-eks
  project: 123-xx
spec:
  blueprintConfig:
    name: minimal
    version: 2.8.0
  cloudCredentials: bharath
  config:
    addons:
    - name: coredns
      version: v1.11.1-eksbuild.4
    - name: vpc-cni
      version: v1.16.0-eksbuild.1
    - name: kube-proxy
      version: v1.29.0-eksbuild.1
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceTypes:
      - t3.large
      maxSize: 2
      minSize: 2
      name: ng1
      version: "1.29"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: bharat-eks
      region: us-west-2
      tags:
        email: bharath.reddy@rafay.co
        env: dev
      version: "1.29"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
