apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: mks-test
  project: 123-xx
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    kubernetesVersion: v1.29.4
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: x86_64
      hostname: bharath-ee-test
      operatingSystem: Rocky9.1
      privateIP: 11.0.1.228
      roles:
      - Worker
      - ControlPlane
      ssh: {}
  type: mks
