apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: newaddon
  project: bharath
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/newaddon/myapp-0.3.0.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: kbr
  placement:
    selector: rafay.dev/clusterName=prod-test
