apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: secret
  project: bharath
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/secret/secret.yaml
    type: Yaml
  namespace: kbr
  placement:
    selector: rafay.dev/clusterName=importbharath
  version: secret-v1-202403220457320000
