apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test-qo
  project: bharath
spec:
  artifact:
    artifact:
      catalog: default-helm
      chartName: simple-nginx
      chartVersion: 0.1.0
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: bharath
  placement:
    selector: rafay.dev/clusterName=bharath-mks
  version: test-qo-v1
