apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test-nginx
  project: bharath
spec:
  artifact:
    artifact:
      catalog: default-helm
      chartName: simple-nginx
      chartVersion: 0.1.0
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: kbr
  placement:
    selector: rafay.dev/clusterName=bharath-eks1-23-02-2023
  version: test-nginx-v1
