apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: test234
  project: bharath
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/test234/test234.yaml
    type: Yaml
  namespace: kbr
  placement:
    selector: rafay.dev/clusterName=importbharath
