apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: demoaddo1n345
  project: bharath
spec:
  artifact:
    artifact:
      paths:
      - name: file://test.yaml
    type: Yaml
  namespace: kbr
  sharing: {}
  version: v1
