apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: helm
  project: bharath
spec:
  base:
    name: default
    version: 1.17.0
  customAddons:
  - name: test
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
