apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: imp
  project: bharath
spec:
  base:
    name: default
    version: 1.25.0
  defaultAddons:
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
