apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: kbr
  project: bharath
spec:
  base:
    name: default
    version: 1.19.0
  customAddons:
  - name: kbr
    version: "1"
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  sharing:
    enabled: true
    projects:
    - name: defaultproject
  type: custom
  version: "3"
