apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test-custom-123
  project: bharath
spec:
  base:
    name: default
    version: 1.21.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: "1"
