apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test
  project: bharath
spec:
  base:
    name: default
    version: 1.12.0
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v2
