apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test-opa-1
  project: bharath
spec:
  base:
    name: minimal
    version: 1.22.0
  driftWebhook:
    enabled: true
  opaPolicy:
    opaPolicy:
    - name: kbr
      version: v1
    profile:
      name: default
      version: latest
  type: custom
  version: v2
