apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: template4
  namespace: default
spec:
  encryptedData:
    hook.terraform.deploy.init.before.infracost.options.container.env_vars.DOWNLOAD_TOKEN: AQA072tVpFY1V7UoZ1WvQEY0nAgfy9X1RZRb9ciPbEOGZrh2vN8rr1W0+OGNUQRLeFY8XQJmfwY9yjuMWD0LR9tmSQSfvWWWgEToaGizj9U+REDARDf/rhIIttR4iprMQXhFryPJiHOWE4+f9pHtA80dQ1ZZoMxK3GXCqd34+yHARqjYtPf9v0R2qfWuF3J2glYrarm1IP0A7V5riwfKBcE7TSTK19mqL+4pCB3rh69zUPSvSw6UR1NQKgjlwvxD4h/mlmayp107dshdMe+f2n1OhrtnXMxnldTnv7aYNYGc+4IiQPk78d+4XRfABeg0OedfYVXw/375pE7b9FoDIeKjkTsvmeuimU/JTuLcLGaXlZNPutcqqtrMxTQtUFMly/QdZ1nRp9WnwR5sL79LvB93qeRcGVgCF37VYSXjxNvnawP51tDSHu9jeb2+tDErVWtaExVThi+1tzuzojoa74c=
    hook.terraform.deploy.init.before.infracost.options.container.env_vars.DOWNLOAD_URL: AQBXvPCutZWh2bEgqCUnjgelK7ll/ublLPk6TFEje4OXzdZkuXqlo3ex5lb/jeNH3u8amlCgJ28xWLnHLs9QnQ66sUqUiFN7WSHVufOv2zlJs9SJcu1Y26yyIMq2sbY6AYZOXN2W7e3ijpSaQOF83B5acUUtGkJN2dHF01SQUCub80UN7uQ2fnmMvg9hYRseKtvdUJWPbhacx5ozfVisUEJ3R45FtcEHSNrj0zbg73nYIANZ8trFhVJRkj5PeIcWCT6ZTCsvmGNGQhAFERNakXg1Tx1Rk7x1Z9X7rZODkBdcXSS/w4bV4e6qu6mX/VRMw5im+PiMBUq2iEJ01L9B/BhAkTroAQss5hx2fQ41o+PovCGG5n8BbAm6Gbs6zeKy4PF/zRa6DpHsDGTFDrQwC5zJwcjCEg8AjrbZaqV5guvUXCpLmY30rqVNACpTOqFaxISxyKPoKGHoAReLGF/a
    hook.terraform.deploy.output.before.webhook.options.http.headers.X-TOKEN: AQCSl1Yk/8PRATwyXJMf4cWrggQwAdJrJipoD+H7ia/rPobsjF7fd9dmEuRzN2QyDpONWB3F+Nwwxi0PcfLczy09RcVZjzFidXAp7gZrJXyu9mYLcC6d/6cvz1aRoz/aC4p33gxdngaeZtKPCyFiKiMrMP1NUgs/D7/XSQzz0aNHHcJ5M5sYYrjTlc8wLij9q0cqBfBE2yV4RjmZDBnLD6b/YCIY/UJ6X1lNdp3NqUttiQ86yLNjv9+NK1IoNlUHFN72hOwpHOngo3YFaU+jSF1Jm8TqwF6salbtBmpk+ctsKAOnheMrRGX3YgHEit72SdmSMeLRtBfeIyJDuXwvOWIXjUftWw8kI8/VzabQiQRu6WUnyFA2
  template:
    metadata:
      creationTimestamp: null
      name: template4
      namespace: default

