apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: testns-49
  project: bharath
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  networkPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: demo-mkscluster
  resourceQuotas: {}
