apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: testns-50
  project: bharath
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  networkPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: bharath-eks-test4
    - key: rafay.dev/clusterName
      value: import-prod
  resourceQuotas: {}
