apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test
  project: defaultproject
spec:
  base:
    name: default
    version: 2.3.0
  costProfile:
    name: test
    version: "1"
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook: {}
  type: custom
  version: "1"
