apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env1
  namespace: default
spec:
  encryptedData:
    hook.onInit.infracost.options.http.headers.KEY: AQBo1VNOM7JuJeAo2F0dPCR4RudazqrCJmV4AhiyJpFnNoahTE7vQ2kC7OHqeIzzeVYwij5MHbLPXTq/5Xjgl6eaBKzpT479zo6izs53INhNSLmrREPGB9ri6PXQqQPBLzyEw0604K84HQwZ8rW/YKUxMCw9qcQjtd7Rxfd+rozI+r2/LEELjEQnc0BhXyxOO3h6wQYp452wPeMZNlwH0HjjN8jG8yoiqvzgnOFTS0O+M6qFYy/IPU7fhq08ET5TqKUts/aVofwzfEOmAiixv6ZTrwf1JMC2NQ4Js1Bpx8ejJxkqYpg7mXLV6/NlXcSsN+Ej1thSYN8kTFBS2NXYgl+PUCK+kecG6gZRkPG324S8UAwGkQpyCQ==
    hook.onInit.infracost.options.http.headers.TOKEN: AQDESgWyyJU+fcbYvbgLFbCISEzUR3xT1dmaqr/M9LLYJf1Zkg2v/0szfwKROqKlTKOPpIfyo/z0/DjXRQJdrYcIkECxz176DN2gJrvpd8XMIu9vJ8TrRLocivRXw555aHHIyZrX4AM8RzmYM/0yNEHPfgJVa5RNu9KKgudo3Jwi3tzysecUh5oWIKvO/Qh2QxeT34Uw0A8aGRy+fQGQ2PYitR53PnL4uSAnzZDraH7DPheAW1uZ4BK348hUc+hO0jlm/nUXGeBjSmERIz1+Pw6pymsgYF/1SSm2mbS+yik2CtCjLdq9tUKdieJhxWvsBSRslbee/y+xIwOURfWKmyg25KkYH4vJCA+2T2SELx+Mbqo9DMkk6cyo
  template:
    metadata:
      creationTimestamp: null
      name: env1
      namespace: default

