kind: Cluster
metadata:
  name: eks-gitops-cluster2-16-02-2023
  project: bharath
spec:
  blueprint: default
  cloudprovider: bharath
  clusterConfig: null
  cniprovider: aws-cni
  proxyconfig: {}
  type: eks
---
apiVersion: rafay.io/v1alpha5
availabilityZones:
- us-west-2a
kind: ClusterConfig
metadata:
  name: eks-gitops-cluster2-16-02-2023
  region: us-west-2
  version: "1.22"
managedNodeGroups:
- amiFamily: AmazonLinux2
  availabilityZones:
  - us-west-2a
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      albIngress: true
      autoScaler: true
  instanceType: t3.medium
  maxSize: 1
  minSize: 1
  name: managed-ng1
  version: "1.22"
  privateNetworking: true
  volumeSize: 80
  volumeType: gp3
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  nat:
    gateway: Single
