kind: Cluster
metadata:
  name: eks-gitops1-cluster2-16-02-2023-13
  project: bharath
spec:
  blueprint: minimal
  cloudprovider: varun-eks
  clusterConfig: null
  cniprovider: aws-cni
  proxyconfig: {}
  type: eks
---
apiVersion: rafay.io/v1alpha5
availabilityZones:
- us-west-2a
- us-west-2b
kind: ClusterConfig
metadata:
  name: eks-gitops1-cluster2-16-02-2023-13
  region: us-west-2
  version: "1.22"
  # tags:
  #   env: "dev"
  #   email: "bharath.reddy@rafay.co"
managedNodeGroups:
- amiFamily: AmazonLinux2
  availabilityZones:
  - us-west-2a
  - us-west-2b
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      albIngress: true
      autoScaler: true
  instanceType: t3.medium
  maxSize: 1
  minSize: 1
  name: managed-ng1
  version: "1.22"
  privateNetworking: true
  volumeSize: 80
  volumeType: gp3
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
  nat:
    gateway: Single
