apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ttyl
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBn+JpPXnsb6WvFuIkTEEOg3B9qnE5Rm3FMM4dz1wzbHX8elyg/5hGJC8fGdPRcFrFmwbn2c7qV1h1tJLiAjnZ8Zu2kyxXgnimeswxnmPJrYbbcYmuGzD4Ynes/iRsIrHZes/GX+E4Re756xIjLEABNcnzpbIhOhY8KQFFk2u5PPYtr+IxYrESPdJD9WuxcxE0aEkfceE8C0v0ygl8MZiZWNhbiv6jfEg9N2A+R6KzvfaK/ojAJOegDOFWV8vZMl43wDfUDKIYjJQYwynHoJY/c/K3M8e0B6m8tyIaQWqFr+D9oyEnqgcQmHOW+8+36jfTMA80bDhg+YL/QEPSYmbrqjK4qhfEMNzQT7vQ8k9BTwApLnGPDnG4cLVnt3a59JhQM2rTkjvJUbCb1Xed4FyMATZegz+L67jy7
  template:
    metadata:
      creationTimestamp: null
      name: ttyl
      namespace: default

