apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: your-app
  namespace: default
spec:
  encryptedData:
    password: AQBf0b5/pRbFUjDHEgXAl3NAH5eJGPmuiqQmd/L/0tM802xxIva1h9p1pHp7jys5vZ9wIKeHqnfrQsTjajtIQfzxxs9WzWwkj71J0MYxFb+6yhz2ns2T2Hn8o/WwZ2258vF+yg/QYvrTdmOrojFKtD/t2SydEyqdHghu4HZX9M0ck4bRAGFhFI6ZtgIGGrgsDiNKc5vJ1e2TfA2iOZH034lXQg6DxTmoqfzhCRR9xGoPyjy+goe3Ku93G5+HwfkXVT4i31ioLkSyauzCXugYwlGeefjufrkpmIAMYeheypQMHYP2fCumXYg0GBA4F7y5qu+PBWeMM0ye8VnC1EMXkurDZpgJPgnMVKIwj71/daeC4zuabkO3LQLT73UhgN8SIHgz7GKoYuYB36r9A8joU1Z7nP9XzSud/uDJ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: your-app
      namespace: default