apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: your-app
  namespace: default
spec:
  encryptedData:
    password: AQBCz5RNMCq71YTuokXPWBdyCNpW0a88BkMmhihEgOd2lvj0s+jwIFcBMVAQS8GFU02zQ52jdrS71BJDkhM2WzKnrJNfFvz4aNZRL88I5+LZsu5JzL8PrFCde8II9LQmtAlqK+weXrLBQwJR9K/UdqfwjwTDmhSuxbmCvRQJiwCNgzf8gke+nGPeSNxiUa7IHo82fWqqmUFaVnmnUbdCKfdVIIzyT4MGJBUtQRk3qB09rVd3C5+6dq8xRnrZIJC9OMIJtk+DFgBYWUNpUAlud8yWWFDqDdw2wmbylOCBba+u1gOARDTl5IchBdb2mStytyeBP+UY5EaVy6EMUUJtWe2xhCrTzOhLrf6SaqPbR+OeQBGQE4zkITKAK3Fz+fKlCVax9iAqMRsUEvPMvCq26HWPcFaQMV+YMaLl
  template:
    metadata:
      creationTimestamp: null
      name: your-app
      namespace: default