apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drive-test-1
  namespace: default
spec:
  encryptedData:
    driverconfig.container.envs.ENVPROCESSOR_ENVIRONMENT_NAME: AQBPHf5OiiLSLrIgvakEEKo0JBOOIAWoelP2Ik+ydgyo1ZXyN85fvLAXQxnsXcqN63Dp0j7j36S6rFcCoP6ozW3fPm6F+wL0bbjXCvAKKYOeuRSWG5eeifLN2C4sEAhSjx8HeAy4s1I+LXhiFvr+VwPef/qXb7774ro6PjcMQO743hyf8fix+IwnY92C5bEW+8BmGCjk9YA49i1xNO12NYjwF5NBBxKbcOJ6i1QrzE+cpapdu0521UPEkdj8sT/KsTkD+FYQ+tUpkO8KyTadgY33fEdFitmtz3Yr9DqxRT1KRQKmFL2vpTvw2x3kvrEv9IkACulkNKMAaBcqnERMtKOw1DaxopgiGjpjW+9Ane+gcV7DUlpeIiWjPKg85IpcuvA0dics1W6DTZkAqheTvsn4+Q==
    registry_credentials: AQBB/dXcGa+m9MUOJ72dobJAMMUGTp6kNQ0K86qVht5mZJ+1iS3//HlUB2A59E9D742ffpVSH3xPT49a2lGPxsKXXUorK14PzWKC4/3HDfW1luotiDsiy1gTaeiicMPXbJwfgxRXWw1kFPn8dALrXBtxL97VKxy3t7EPCUfwUbJEBZlTCZ6zkdYUQNVrNGfTfcdZyg8Ar9FQ9Fx/lgOibrFrHkmPSEm/HFIKa2NeYZNrOBMkyAFSLD26xBwviDuRRSX94NvQnaVUzwgopQE7YoZzVy9tvbECArTPFXRY/NtMhrqBmBTHApPYwNmK2s5YVVwy/uXr9Beu8ZxPUlp9TJmoVu4a+Sdt/mratYcHXqlky14QLkUY
  template:
    metadata:
      creationTimestamp: null
      name: drive-test-1
      namespace: default

