apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drive-test-1
  namespace: default
spec:
  encryptedData:
    driverconfig.container.envs.ENVPROCESSOR_ENVIRONMENT_NAME: AQAeHtz00r2FFw6JJ2//gSQ88Ais/CorjW5PSgeDIu8ZHid8Oc3bx29Dsl+0BjEs61HV1sFn5+6usL88/gXb+NvpdWQWDejI/YPGaB3ed1R27TMnoTkmdyqNXFWbMnb+kYoHukBrYhPpeFzGa+DLrQ0ILPieNFai/I38Q7MyqOUrtp5IiJ9c9cAAV+MvhNm/idNhQnEHsZNaZbop5EEFWM8FpS4KZmVJcse1351p51l/ZkCrZO/nHebap4RtEYOcdLkRjBVgvCQlj1JpDoNKrU3Q8olH0qOoWeyJayD33TwDjRVLXDHiJWpJlljmPC7GuyN9wOGBHx9EwR0n1M1LQs7/XL5RCj73kouF0+Z71rbTnf/cgHj5rNto+TXl7+l2xDQ9LFUQRfqQAEGaQ/LqdEhLgg==
    registry_credentials: AQAgT95nmTO+2SJi/00cANv5bzMLt8BHeho931krBxBIKeAgEhp2rvmCcNCsbkVeMCe7FzYhNLsg0bvx30Bmeq0tfKhBvMpOdyks5VjBJCKzVCFwFHBed1HnqtLYJXjIpM0rrEy7DSzTMuoaYmZ8LCoQca6deP00e5x1kIwXRifXfG1DKKrVD62Fiv8fU84gGeXt9d0Z0IurHVlvMSR1zf1y9igNYteB3ic6PwdMB3SjXv1S6gZDB5gZdyD20iBMtGy6dsT/PUOovy3LGbUcBiKrYxSkJCg3qMcCVta9pflvIXJ3pkcDB1oHMWbwtz30RqXX2Sj3sHMNX0sUD72d8vdpxyczz7pNHrf+68yHthFUe1hCkNwM
  template:
    metadata:
      creationTimestamp: null
      name: drive-test-1
      namespace: default

