apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drive-test-1
  namespace: default
spec:
  encryptedData:
    driverconfig.container.envs.ENVPROCESSOR_ENVIRONMENT_NAME: AQDJhJfl0mB5hxsPfoT6jEV9ocBAKChEdm5DnT/SwcW88q7kIBTuLDPnF5qkLjZpRMWrSWPehJkoVsYs1ZETsCfLI9CvfHQCJXe4PHmAlH+6pVczIwePQBKZpYQHoN89Hm8+lq3yXmFnYE0FIo94nUdJTeY8+QYzin5taGztv7XwuD/nT71u6AGnSGMaQnHRzsCZaprcJ4/I6/IkDHL9cbapeVK88VwCyB/5BwurtLXFC9rNGI6S6ZzWt5u8Tkci2Qa5EaX9yYgu66z97rwmOuW6+G81DSOfY5GuMqboMlH1mz/FXVyaiHR7GPq99laQS8Tys2/VMB93aAjIb0dYUWjAi4f5w4On9P4+60T20MZWt84gXmjgNJYfhD4rzpRjLySNRKHlSOtiq3uwkQdvfIbNIA==
    registry_credentials: AQC2q1CuM7PONm7L91mY0059b+mx+DkCrZxMwVP/NFilMLmxemdw23KX0xTZeNJV9I4ILTxBpCn27xfY6lLrcfiXk2lVWYRIslpTiJ954nhKRssNherZ6sC0lKDQKa0LKhIjbf5vssHVlm1hRe5b0PrNnUVaIZDwQZNevp663RMhQ0YKoWkt+kllvBBP5+3Vaz60aSy2UEqgJ9sMvlv+K3JGkYhPKkdF+1K86Qf4Xp34canV1CjeBBQE3KgMpScvABxhZBMUIj1DHXWXaITUaMP/9vXWZK48uKzVDRfO3LABYVgpgCI/Sbb7tOyBYYLlcf5klvK0vc4rEp2CU032OEPOEKEWZ20TeuuMyNeRsyBN+rD2JoOp
  template:
    metadata:
      creationTimestamp: null
      name: drive-test-1
      namespace: default

