apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: bharath-role-eks-cluster
  project: bharath
spec:
  blueprintConfig:
    name: minimal
    version: Latest
  cloudCredentials: bharatrole
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
    addons:
    - name: coredns
    - name: vpc-cni
    - name: kube-proxy
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceTypes:
      - t3.large
      maxSize: 1
      minSize: 1
      name: ng-bharath
      version: "1.30"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: bharath-role-eks-cluster
      region: us-west-2
      tags:
        email: bharath.reddy@rafay.co
        env: dev
      version: "1.30"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
