apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: bharath-mks-cluster-template
  project: bharath
spec:
  blueprint:
    name: default
    version: latest
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubeletExtraArgs:
      cpu-manager-policy: none
      max-pods: "200"
    kubernetesVersion: v1.30.8
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: bharath-template2
      kubeletExtraArgs:
        cpu-manager-reconcile-period: 40s
        max-pods: "400"
      labels:
        app: infra
        infra: "true"
      operatingSystem: Ubuntu22.04
      privateIP: 11.0.1.107
      roles:
      - Worker
      ssh:
        ipAddress: 144.24.18.107
        port: "22"
        privateKeyPath: /home/bharat/Downloads/ssh-key-2025-01-23.key
        username: ubuntu
    - arch: amd64
      hostname: bharath-template1
      kubeletExtraArgs:
        cpu-manager-reconcile-period: 30s
        max-pods: "300"
      labels:
        app: infra
        infra: "true"
      operatingSystem: Ubuntu22.04
      privateIP: 11.0.1.168
      roles:
      - ControlPlane
      - Worker
      ssh:
        ipAddress: 129.146.19.230
        port: "22"
        privateKeyPath: /home/bharat/Downloads/ssh-key-2025-01-23.key
        username: ubuntu
  type: mks
