apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: bharath-eks-21-02-02023
  project: bharath
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: varun-eks
  config:
    metadata:
      name: bharath-eks-21-02-02023
      region: us-west-2
      version: "1.24"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 1
      minSize: 1
      name: ng-f3d82fa8
      version: "1.24"
      volumeSize: 80
      volumeType: gp3
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
status:
  blueprint:
    name: minimal
  conditions:
  - reason: pending
    status: "False"
    type: ClusterRegisterSucceeded
  - reason: pending
    status: "False"
    type: ClusterCheckInSucceeded
  - reason: pending
    status: "False"
    type: ClusterNodeSyncSucceeded
  - reason: pending
    status: "False"
    type: ClusterBlueprintSyncSucceeded
  - reason: pending
    status: "False"
    type: ClusterNamespaceSyncSucceeded
  - reason: pending
    status: "False"
    type: ClusterReady
  createdAt: "2023-02-21T09:41:36Z"
  displayName: bharath-eks-21-02-02023
  extra:
    vaultIntegration: {}
  id: 28djxlk
  name: bharath-eks-21-02-02023
  provisionStatus: INFRA_CREATION_FAILED
