apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: bharat-eks-cluster1
  project: bharath
spec:
  blueprintConfig:
    name: minimal
    version: 3.1.0
  cloudCredentials: bharath
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceTypes:
      - t3.large
      maxSize: 2
      minSize: 1
      name: ng-bharath
      version: "1.30"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: bharat-eks-cluster1
      region: us-west-2
      tags:
        email: bharath.reddy@rafay.co
        env: dev
      version: "1.30"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
