apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: bharath-roky1
  project: bharath
spec:
  blueprint:
    name: nginxbp
    version: "5"
  config:
    autoApproveNodes: true
    kubernetesVersion: v1.28.5
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: x86_64
      hostname: bharath-rocky-ci2
      operatingSystem: Rocky9.1
      privateIP: 11.0.1.24
      roles:
      - Worker
      - ControlPlane
      ssh: {}
    - arch: x86_64
      hostname: bharath-rocky-custom-ci3
      operatingSystem: Rocky9.1
      privateIP: 11.0.1.4
      roles:
      - Worker
      ssh: {}
  type: mks
