apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: bharath-eks-clustertest2
  project: bharath
spec:
  blueprintConfig:
    name: default
    version: 3.1.0
  cloudCredentials: bharath
  config:
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          appMeshPreview: false
          autoScaler: true
          certManager: false
          cloudWatch: false
          ebs: false
          efs: false
          externalDNS: false
          fsx: false
          imageBuilder: true
          xRay: false
      instanceType: t3.large
      labels:
        app: infra
        dedicated: "true"
      maxPodsPerNode: 50
      maxSize: 2
      minSize: 0
      name: ng-1
      privateNetworking: true
      spot: false
      tags:
        bp: minimal1
      version: "1.31"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          appMeshPreview: false
          autoScaler: true
          certManager: false
          cloudWatch: false
          ebs: false
          efs: false
          externalDNS: false
          fsx: false
          imageBuilder: true
          xRay: false
      instanceType: t3.large
      labels:
        app: infra
        dedicated: "true"
      maxPodsPerNode: 50
      maxSize: 2
      minSize: 0
      name: ng-2
      privateNetworking: true
      spot: false
      tags:
        bp: minimal21
      version: "1.30"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    metadata:
      name: bharath-eks-clustertest2
      region: us-west-2
      tags:
        email: bharath.reddy@rafay.co
        env: dev
      version: "1.31"
    network:
      cni:
        name: aws-cni
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
