apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: bharath-eks-clustertest2
  project: bharath
spec:
  blueprintConfig:
    name: default
    version: Latest
  cloudCredentials: bharath
  config:
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    iam:
      serviceAccounts:
      - attachPolicy:
          Statement:
          - Action: ec2:Describe*
            Effect: Allow
            Resource: '*'
          - Action:
            - ec2:AttachVolume
            Effect: Allow
            Resource: '*'
          - Action: ec2:DetachVolume
            Effect: Allow
            Resource: '*'
          - Action:
            - elasticloadbalancing:*
            Effect: Allow
            Resource:
            - '*'
          Version: "2012-10-17"
        metadata:
          name: test-irsa
          namespace: yaml1
        roleOnly: false
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          appMeshPreview: false
          autoScaler: true
          certManager: false
          cloudWatch: false
          ebs: false
          efs: false
          externalDNS: false
          fsx: false
          imageBuilder: true
          xRay: false
      instanceType: t3.large
      labels:
        app: infra
        dedicated: "true"
      maxPodsPerNode: 50
      maxSize: 2
      minSize: 1
      name: ng-1
      privateNetworking: true
      spot: false
      tags:
        bp: default
      version: "1.30"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      iam:
        withAddonPolicies:
          albIngress: false
          appMesh: false
          appMeshPreview: false
          autoScaler: true
          certManager: false
          cloudWatch: false
          ebs: false
          efs: false
          externalDNS: false
          fsx: false
          imageBuilder: true
          xRay: false
      instanceType: t3.large
      labels:
        app: infra
        dedicated: "true"
      maxPodsPerNode: 50
      maxSize: 2
      minSize: 1
      name: ng-2
      privateNetworking: true
      spot: false
      tags:
        bp: default
      version: "1.30"
      volumeEncrypted: false
      volumeIOPS: 3000
      volumeSize: 80
      volumeThroughput: 125
      volumeType: gp3
    metadata:
      name: bharath-eks-clustertest2
      region: us-west-2
      tags:
        email: bharath.reddy@rafay.co
        env: dev
      version: "1.30"
    network:
      cni:
        name: aws-cni
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
