apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: mks-bharat
  project: bharath
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubeletExtraArgs:
      max-pods: "100"
    kubernetesVersion: v1.30.4
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: bharat-mks-test
      operatingSystem: Ubuntu20.04
      privateIP: 11.0.1.134
      roles:
      - Worker
      - ControlPlane
  proxy: {}
  type: mks
