apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: mks1
  project: bharath
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.30.4
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: x86_64
      hostname: bharath-rockytest
      operatingSystem: Rocky9.1
      privateIP: 11.0.1.92
      roles:
      - ControlPlane
      - Worker
  proxy: {}
  type: mks
