apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rocky6
  project: bharath
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    kubernetesVersion: v1.28.5
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: x86_64
      hostname: bharath-rocky9-ci
      operatingSystem: Rocky9.4
      privateIP: 10.1.0.86
      roles:
      - ControlPlane
      - Worker
      ssh: {}
  type: mks
