apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    check1: value1
    check2: value2
  name: test-mks-bharath
  project: bharath
spec:
  blueprint:
    name: default
    version: latest
  config:
    autoApproveNodes: true
    kubernetesVersion: v1.31.0
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: bharath-newtest
      operatingSystem: Rocky9
      privateIP: 11.0.1.142
      roles:
      - ControlPlane
      - Worker
      ssh:
        ipAddress: 129.146.243.189
        port: "22"
        privateKeyPath: /home/ujwal/Downloads/ssh-key-2024-10-28.key
        username: rocky
  type: mks
