apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: test
  project: bharath
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    kubernetesVersion: v1.27.13
    network:
      cni:
        name: Calico
        version: 3.26.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
  type: mks
