apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: warewulf-mks-cluster
  project: bharath
spec:
  blueprint:
    name: minimal
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.31.0
    network:
      cni:
        name: Calico
        version: 3.28.1
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: x86_64
      hostname: node2
      operatingSystem: Rocky9.4
      privateIP: 10.0.0.73
      roles:
      - ControlPlane
      - Worker
    - arch: x86_64
      hostname: node3
      operatingSystem: Rocky9.4
      privateIP: 10.0.0.139
      roles:
      - Worker
  proxy: {}
  type: mks
