apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: template2
  namespace: default
spec:
  encryptedData:
    hook.terraform.deploy.init.before.infracost.options.container.env_vars.DOWNLOAD_TOKEN: AQBm9wVvKNoxbAStbmU1jxj3TCRedr7/79XeTX1UhyaPTF6vRBqD9M7ipNpQmsJCRvVtmVk1fkN0xQ+a8J5SOHEPx6q9bPqMWQFEXkbUiwxaSHIjmSYzyQgb1kokOpNe3tyarPlUdubvk7wuNkJlTyR1++qLXlSenXOT/SHlpW7rH/dsO3Mpi2Efj4kG9yA0YFzdWC0ijplCZcm1NoqSccCux3IjsPkxim81xsVLt2d7s4eMPCMZ1jO4OwAKUCr63GOluR5V+NoV5AnVXV3qWigP6O5m0Kfl38zIHPOy6u/N+1w+Z6aCg9tTWj9d/Nzo08btODP63cwkcAO80140bIh8p8SjXftvCjxT3e7jjGkDAOH6ForGVIxr27jYZwjM5/iMJznc9lOdyAMxF3Pg0CxiVZcw23XGoRO18RkDaK/XDL98WqW1acubOw9gV2C+WvcCQn09a9LZO88yjDen/fY=
    hook.terraform.deploy.init.before.infracost.options.container.env_vars.DOWNLOAD_URL: AQAjND6SpfZ7hjH3uWX6/el1vicWDMnSiYlgnE34OF8/j/ZxucxHEwMSguhi66XOUmJM6Zi6tfZmZuME/eIHOmxPfB9cp8Nsb7ywXeHzmn/XvjHaLnnKvHKphxBZgSpc37BXy+sSXmxmMuIBpHCYtIZdm45Fa9s99UaBp9nAw0YEOsbq7H7nDQ9EycU9zfKZD/Sk29LJ24dNBaYwLI+TugjsJozM7n79x3DYhmGxgRKmdWaDXRvrIyCpOyU5U2xiR/goENIofzqur+Pg6ayf61XCyrKccx8cspM5SCGotaTj4gSURY38Yp4Jm2bnwjXEDKjxzKyzb9FuRfBCQ1/oNm9JziafVr2M96HEWou46nMZsSwrKBhJwU9oxPe2ElnzertcmEiWhBgfCfvv8Qupnef+s7/SEWKjwrgo1+m5tYEngxbJZRfBEeON+i1bUVX+8BkW1UhxsDHUVL0GfJ7t
    hook.terraform.deploy.output.before.webhook.options.http.headers.X-TOKEN: AQDG4LbTQtH7O+rXpXwbfS1ifZjazqx8RxdpLHNK2iVTy8otke5OuCS3txqPQ8aeLSCPGRst93BfMJd+YbECun9F5+SBQWQqcHEerz0tz8yOh8cCXBrqTbVQ/qzGeuFpiRhxQfbjB+cm7JiYuLScU37yRP4pRei+0hDgpBsKCC7jpck9Fo+5Iy/JKBvIX+Jysky5EFbPpInbW9lUT3BmhS1iVU2g6cMKVjo1PuEHX0RMkjPnqKTnZox/b+lv5ILMF2zBBKQNFoOCX9TVLgdvjLFNHtWggT7zYxZxyTkqHygRwnXSCKT7k/kAVce4ATBLZL1/j/N0l8trEtCVrxumYRg5nKJmdB1IPZ1ayYkgzWRLzfWv33zw
  template:
    metadata:
      creationTimestamp: null
      name: template2
      namespace: default

