apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx
  project: bharathtest
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/nginx/nginx.yaml
    type: Yaml
  namespace: testwl
  placement:
    selector: rafay.dev/clusterName=testcluster
  version: nginx-v1-202403070545030000
