apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
    version: 2
  name: constraint1
  project: bharath-test
spec:
  artifact:
    artifact:
      paths:
      - name: test1.yaml
      repository: test1
      revision: master
    options: {}
    type: Yaml
